server:
  port: ${SERVER_PORT:8081}

spring:
  rabbitmq:
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        auto-startup: true
        acknowledge-mode: manual
        concurrency: 5
        prefetch: 10
    host: ${RABBITMQ_HOST:127.0.0.1}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:hmdp}
    password: ${RABBITMQ_PASSWORD}
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ${MYSQL_URL:jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true}
    username: ${MYSQL_USERNAME:hmdp}
    password: ${MYSQL_PASSWORD}
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    lettuce:
      pool:
        max-active: 30
        max-idle: 15
        min-idle: 5
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null

mybatis-plus:
  type-aliases-package: com.hmdp.entity

logging:
  level:
    com.hmdp: debug
